services:
  tc002:
    image: ghcr.io/doitian/ulanzi-tc002:latest
    build: .
    ports:
      - "8008:8008"
    environment:
      TC002_DEVICE_IP: "10.31.3.197"
    volumes:
      - tc002-data:/data

volumes:
  tc002-data:
